### ISSUE TITLE
Mag Portal

### ISSUE THREAD

**Issue by Da3ngo2** [Vateron-Media/Xtream_main#2]
Hello,

First, I would like to thank you for the effort you are putting into this project. I take my hat off to you, great job. Regarding the issue, the MAG portal does not work when accessed through the Smart STB or the MAG device itself. 

Thanks again.

**Comment by Divarion-D** [comment]
Thanks, we'll check it out

**Comment by Divarion-D** [comment]
Fixed in release https://github.com/Vateron-Media/Xtream_main/releases/tag/v1.2.0
